[features]
seeds = false
[programs.localnet]
crowdfunding = "B8R8ubfobZh8A4XwGeAjVymSKhgwWFFfLnpX1xnqdqc6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
